### ISSUE TITLE
How to attach screenhots, logs, video links

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/klov#12]

**Comment by anshooarora** [comment]
It will be automatic once the host and port are set for the klov server using:

```
setKlovUrl("http://localhost:80");
```

I have created a quick demo in my environment and this is how screenshots are being displayed (pointed by the big arrows).

![img](https://user-images.githubusercontent.com/4107384/33326933-4d0ee852-d424-11e7-90c3-8485005b920f.png)

**Comment by saikrishna321** [comment]
path of the screenshot should be absolute ?

**Comment by anshooarora** [comment]
Please upgrade to version `0.0.2` from http://extentreports.com/community/ and try again.  Your current usage should work with klov also.

**Comment by saikrishna321** [comment]
@anshooarora with latest, the images are not getting attached

<img width="920" alt="screen shot 2017-11-29 at 10 28 20 pm" src="https://user-images.githubusercontent.com/4045041/33387985-ae1367aa-d554-11e7-9773-79d581fd3ea6.png">

**Comment by saikrishna321** [comment]
@anshooarora the images are getting displayed when i compare them from the dashboard node

<img width="1399" alt="screen shot 2017-11-30 at 11 13 06 am" src="https://user-images.githubusercontent.com/4045041/33415883-a714d77a-d5bf-11e7-89af-0d43da05f201.png">

When we navigate to the failed test case from the builds it does not display the img

**Comment by anshooarora** [comment]
Hmm I will have to check but if you see the demo app:  http://klov.herokuapp.com/report?id=59d3cd7c0ac0221640e8cc0c (MediaTest), all images are showing even in the build view.

**Comment by saikrishna321** [comment]
hmm .. your right .. i can see under MediaTest

**Comment by saikrishna321** [comment]
@anshooarora here is example with issue 

https://github.com/saikrishna321/extent_reports/tree/klov

**Comment by anshooarora** [comment]
Thanks..  I was able to reproduce this.  It was bad HTML causing it.  Will upload the latest (0.0.3) now.

**Comment by anshooarora** [comment]
Direct download:  https://drive.google.com/open?id=1kNlqu5CLXW22X5-IXEQFuTO5F-khor7n

http://extentreports.com/community/

**Comment by anshooarora** [comment]
Use extentreports version 3.1.2 with klov-0.0.3:

```
<!-- pom.xml -->
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.1.2</version>
</dependency>
```

**Comment by saikrishna321** [comment]
@anshooarora it works fine.. thanks 👍 

Still unsure how to add txt and video files, below does not work 

			test.get().log(Status.INFO,"<a target=\"_parent\" href="
					+ System.getProperty("user.dir") + "/testng.xml" + ">Logs</a>");
			test.get().addScreencastFromPath("filepath");

**Comment by anshooarora** [comment]
It's the API that does not support either.  But we can add this functionality.

**Comment by saikrishna321** [comment]
would be great if its added in the next release

**Comment by asashank** [comment]
Hi,

I am using extent reports (3.1.3) along with klov (0.0.3). While attaching screenshots for failed steps, I am using the below code.

String imagePath = takeScreenshot(screenPath,fileName);
imagePath = "."+imagePath.substring(imagePath.lastIndexOf("/screenshots"));
ExtentTestManager.getTest().log(status, reportStatement,
MediaEntityBuilder.createScreenCaptureFromPath(imagePath).build());

For eg, the image path would be set as "./screenshots/58477b71-c8c6-46d7-9c75-199496d81b9b.png"

Here 2 scenarios are there.
1. **Extent report:** Giving absolute path to the image is working perfectly for extent report and even if i move the report and screenshots folder to any location, it works since its not absolute path. 

2. **Klov report:** If I give absolute path of the image and add log along with screenshot, then it works. If I give relative path, it does not work.

Now, if I change my code to set the image path as absolute, my local extent does not display screenshots, if I move the report folder to another path or rename it since its not having absolute path.

So, is there a way to pass absolute path to the image path and make sure the image is displayed in both extent and Klov?

Thanks,
Aditya Sashank

**Comment by arunkumarkmj** [comment]
Hi Anshoo,

I am also facing same issue as what Aditya mentioned above . I am using relative path to see images on extent report even while sharing it. However the relative path doesn't work for Klov and throws error for file not found. I am using latest version of extent report (3.1.5) and klov (0.1.1) .
Please suggest for any workaround .

Thanks,
Arun
